export const VALOR_MAXIMO_CARACTERES_CLASIFICADOR = 'VALOR_MAXIMO_CARACTERES_CLASIFICADOR';
export const VALOR_MAXIMO_CARACTERES_NIVEL_CLASIFICADOR = 'VALOR_MAXIMO_CARACTERES_NIVEL_CLASIFICADOR';

export const NATURALEZA = {
  Dominio1: 'NATURALEZA',
};

export const TERCERO_JURIDICO = {
  Dominio1: 'TIPOTERCEROJURIDICO',
};

export const TIPO_DOCUMENTO = {
  Dominio1: 'TIPODOCUMENTO',
};

export const TIPO_RESPONSABILIDAD_TRIBUTARIA = {
  Dominio1: 'TIPORESPONSABILIDADTRIBUTARIA',
};

export const TIPO_DIRECCION = {
  Dominio1: 'TIPODIRECCION',
};
