export const ADM = {
  ACCIONES_TOAST: {
    toastTipo: {
      creado: 'success',
      fallido: 'error',
      advertencia: 'warn',
      informacion: 'info',
    },
    toastMensaje: {
      creado: 'Registro exitoso',
      actualizar: 'Registro exitoso',
      fallido: 'Registro fallido',
      advertencia: 'Advertencia',
      informacion: 'Informacion',
    },
  },
  ACCION_CREAR: 'crear',
  ACCION_EDITAR: 'editar',
  ACCION_ACEPTAR: 'Aceptar',
  ACCION_CANCELAR: 'Cancelar',
  PERFIL_ADMINISTRATIVO: 'ADM',
  PERFIL_NEGOCIO: 'NEG',
  ESTADOS_GENERAL: [
    { id: 'Si', valor: true },
    { id: 'No', valor: false },
  ],

  LOCALE_CO: 'es-CO',
  ACCIONES_CONFIRM: {
    buttons_class: {
      acceptButtonStyleClass: 'p-button-success colorVerdeMHCP',
      rejectButtonStyleClass: 'colorRojoMHCP mt-1',
    },
    delete: {
      message: '¿Desea eliminar el registro seleccionado?',
      header: 'Eliminar registro',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Si, eliminar',
      rejectLabel: 'No, cancelar',
    },
    deleteCalendario: {
      message:
        '¿Está seguro que desea eliminar los tipos de día seleccionados?',
      header: 'Eliminar registro',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Si',
      rejectLabel: 'No',
    },
    deleteParticipantes: {
      message:
        'Ha quitado la selección del tipo de tercero jurídico, esto eliminará la información registrada en la sección "Participantes". ¿Desea continuar?.',
      header: 'Eliminación datos participantes',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Aceptar',
      rejectLabel: 'Cancelar',
    },
    validacionNumeroYtipoDocumentoJuridico: {
      message:
        'Ya se encuentra creado un tercero con el número de Número de identificación ingresado  y otro Tipo  de identificación, ¿está seguro de continuar con la creación del tercero?".',
      header: 'Validación existencia numero documento',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Aceptar',
      rejectLabel: 'Cancelar',
    },
    validacionNumeroNatural: {
      message:
        'Ya se encuentra creado un tercero con el Número de identificación ingresado, ¿está seguro de continuar con la creación del tercero?".',
      header: 'Validación existencia numero documento',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Aceptar',
      rejectLabel: 'Cancelar',
    },
    activarDireccion: {
      message: 'Está seguro de activar la dirección?',
      header: 'Activar direccion',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Aceptar',
      rejectLabel: 'Cancelar',
    },
    inactivarDireccion: {
      message: 'Está seguro de inactivar la dirección?',
      header: 'Inactivar direccion',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Aceptar',
      rejectLabel: 'Cancelar',
    },
    activarTercero: {
      message: '¿Está seguro de reactivar el tercero en el sistema?',
      header: 'Activar tercero',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Aceptar',
      rejectLabel: 'Cancelar',
    },
    inactivarTercero: {
      message: '¿Está seguro de inactivar el tercero seleccionado?',
      header: 'Inactivar tercero',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Aceptar',
      rejectLabel: 'Cancelar',
    },
    confirm: {
      message: '¿Está seguro de finalizar el proceso que lleva acabo?',
      header: 'Guardar proceso',
      icon: 'pi pi-info-circle',
      acceptLabel: 'Si, guardar',
      rejectLabel: 'No, continuar',
    },
    cancel: {
      message: '¿Está seguro de cancelar la operación actual?',
      icon: 'pi pi-exclamation-triangle',
      acceptLabel: 'Si',
      rejectLabel: 'No',
      style: { width: '40vw' },
    },
  },
  TRANSLATE_CALENDAR: {
    dayNames: [
      'Domingo',
      'Lunes',
      'Martes',
      'Miércoles',
      'Jueves',
      'Viernes',
      'Sábado',
    ],
    dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Sab', 'Dom'],
    dayNamesMin: ['Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa', 'Do'],
    monthNames: [
      'Enero',
      'Febrero',
      'Marzo',
      'Abril',
      'Mayo',
      'Junio',
      'Julio',
      'Agosto',
      'Septiembre',
      'Octubre',
      'Noviembre',
      'Diciembre',
    ],
    monthNamesShort: [
      'Ene',
      'Feb',
      'Mar',
      'Abr',
      'May',
      'Jun',
      'Jul',
      'Ago',
      'Sep',
      'Oct',
      'Nov',
      'Dic',
    ],
    today: 'Hoy',
    clear: 'Limpiar',
    dateFormat: 'mm/dd/yy',
    weekHeader: 'Wk',
    firstDayOfWeek: 0,
  },
  NO_PGN: 'No PGN',
  PGN: 'PGN',
  TIPO_PERFIL: 'TIPOPERFIL',
  ROLES: 'ROLES',
  PERDIDA_DATA: 'Missing data...',
  ESTADO_HTTP_200: 200,
  ESTADO_HTTP_301: 301,
  ESTADO_HTTP_404: 404,
  ESTADO_HTTP_500: 500,
  ESTADO_HTTP_503: 503,
  ESTADO_EXITOSO: 'success',
  ESTADO_FALLIDO: 'error',
  ESTADO_ADVERTENCIA: 'warn',
  ESTADO_INFORMACION: 'info',
};
